### ISSUE TITLE
Drop CLA from translations

### ISSUE THREAD

**Issue by comradekingu** [LStranger/foxeye#3]
I don't sign CLA agreements, and I would like to contribute.

https://hosted.weblate.org/contributor-agreement/foxeye/pot/?next=/projects/foxeye/pot/nb_NO/
It is sort of pointless, because one would have to prove intent for it to even matter.

:)

**Comment by LStranger** [comment]
Thank you very much. I am new with Weblate, just learning. :)

**Comment by comradekingu** [comment]
@LStranger You can remove it in https://hosted.weblate.org/settings/zen/foxeye/pot :)

**Comment by LStranger** [comment]
Sure. Done now. It appeared Weblate was unavailable when I received your request.
